name: CMake

on: [push, pull_request, fork]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shared: [ON, OFF]
        exclude:
          # CMake don't copy DLLs to exe output, skip for now
          - os: windows-latest
            shared: ON
    env:
      BUILD_SHARED_LIBS: ${{matrix.shared}}
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Build
      run: |
        cmake --preset Release
        cmake --build --parallel --preset Release
    - name: Test
      working-directory: build
      run: ctest -C Release --output-on-failure
    - name: Post Test
      run: git diff --exit-code

  memcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Build
      run: |
        sudo apt-get install -y valgrind
        cmake --preset Debug
        cmake --build --parallel --preset Debug
    - name: Test
      working-directory: build
      run: |
        ctest -T memcheck --overwrite MemoryCheckCommandOptions="--leak-check=full --show-leak-kinds=all --error-exitcode=100"
        awk 'FNR==1 {print "\n\n\n\n\n\t", FILENAME, "\n"}{print}' Testing/Temporary/MemoryChecker.*.log
    - name: Post Test
      run: git diff --exit-code

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Build
      run: |
        cmake --preset Debug -DBUILD_COVERAGE=ON
        cmake --build --parallel --preset Debug
    - name: Test
      working-directory: build
      run: ctest -T test -T coverage
    - name: Post Test
      run: git diff --exit-code
    - uses: codecov/codecov-action@v2

