name: CMake

on: [push, pull_request, fork]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shared: [ON, OFF]
        exclude:
          # CMake don't copy DLLs to exe output, skip for now
          - os: windows-latest
            shared: ON
    env:
      CMAKE_BUILD_TYPE: Release
      BUILD_SHARED_LIBS: ${{matrix.shared}}
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Build
      run: |
        cmake --preset default
        cmake --build --parallel --preset default
    - name: Test
      working-directory: build
      run: ctest -C ${{env.CMAKE_BUILD_TYPE}} --output-on-failure

  memcheck:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Debug
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - name: Build
      run: |
        sudo apt-get install -y valgrind
        cmake --preset default
        cmake --build --parallel --preset default
    - name: Test
      working-directory: build
      run: ctest -T memcheck

